seed: 11
llm:
  provider: openai
  model: gpt-4o-mini
  max_tokens: 384
retrieval:
  top_k: 6
  chunk_size: 700
  chunk_overlap: 120
  use_hpo_rerank: true
privacy:
  scheme: dp_sparse_vote
  m_voters: 8
  epsilon_per_vote: 0.5
  delta: 1e-6
  max_total_epsilon: 10.0
  svt:
    threshold: 0.65
    epsilon_gate: 0.25
    epsilon_report: 0.25
    max_spend_tokens: 128
