seed: 7
llm:
provider: mock # mock|openai
model: debug-mock
max_tokens: 256
retrieval:
top_k: 6
chunk_size: 800
chunk_overlap: 120
use_hpo_rerank: true
privacy:
scheme: dp_vote
m_voters: 6
epsilon_per_vote: 0.5
delta: 1e-6
max_total_epsilon: 6.0